# Generated by Django 3.0.3 on 2020-07-10 09:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('incidentDesc', models.TextField(blank=True, max_length=500, null=True)),
                ('incidentTime', models.TimeField(blank=True, null=True)),
                ('incidentdate', models.DateField()),
                ('inciloc', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=50)),
                ('cause', models.CharField(max_length=200)),
                ('actionTaken', models.CharField(max_length=200)),
                ('types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('envIncident', 'envIncident'), ('injury_illness', 'injury_illness'), ('property', 'property'), ('vehicle', 'vehicle')], max_length=43, null=True)),
                ('reporter', models.CharField(max_length=100)),
            ],
        ),
    ]
